- if-wsl:
    - shell:
        - sudo apt install -y fish finger direnv
        # For en_US locales
        - sudo apt install -y language-pack-en
- link:
    ~/.hushlogin: configs/shell/.hushlogin

- shell:
    # $PWD for these scripts is always the canonical path to the dotfiles root
    - configs/shell/setup-fish
