#!/usr/bin/env bash
set -ef

# Preemptively asks for sudo and keeps the session for as long as we're running.
# Credit: https://gist.github.com/cowboy/3118588
sudo -v -p "We need sudo to perform certain tasks. Please authenticate [$(whoami)]: "
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

CONFIG="dotbot.yaml"
DOTBOT_DIR="_vendor/dotbot"

DOTBOT_BIN="bin/dotbot"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"
git submodule update --init --recursive "${DOTBOT_DIR}"

"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
