#!/usr/bin/env bash
set -euf

if ! [ -x "$(command -v brew)" ]; then
  curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install | /usr/bin/ruby
fi

brew bundle --file=macos/Brewfile
